[package]
name = "worldgen"
version = "1.0.1"
authors = [ "mhsjlw" ]
license = "MIT"

[lib]
name = "worldgen"
crate-type = [ "dylib" ]

[dependencies]
neon = "0.1"
voxel_worldgen = "0.1"
nalgebra = "0.5"
noise = "0.5"
rand = "0.4"
