[package]
name = "worldgen"
version = "1.0.1"
authors = [ "mhsjlw" ]
license = "MIT"

[lib]
name = "worldgen"
crate-type = [ "dylib" ]

[dependencies]
neon = "*"
voxel_worldgen = "0.1"
nalgebra = "0.18"
noise = "0.6"
rand = "0.7"
